server:
  port: 8080
  error:
    include-message: always
spring:
  flyway:
    locations: classpath:db/migration
  main:
    web-application-type: servlet
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5332/mydb
    password: 110011
    username: smite
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  sql:
    init:
      mode: always