server:
  port: 8080
  error:
    include-message: always
spring:
  main:
    web-application-type: servlet
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5332/customer
    password: 110011
    username: amigoscode
  jpa:
    hibernate:
      ddl-auto: create-drop # БД каждый раз будет обновляться при запуске / остановке приложения
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false