name: CI - Build Backend

on:
  pull_request:
    branches:
      - main
    paths:
      - Backend/**

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14.7
        env:
          POSTGRES_USER: smite
          POSTGRES_PASSWORD: sadrrainbow
          POSTGRES_DB: mydb
        ports:
          - 5332:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    defaults:
      run:
        working-directory: ./Backend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: build and run ITs with Maven
        run: mvn -ntp -B verify